version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    working_directory: ~/hello-world
    steps:
    - checkout
    - restore_cache:
        key: hello-world-{{ checksum "pom.xml" }}
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: hello-world-{{ checksum "pom.xml" }}
    - run: mvn package
    - store_test_results:
        path: target/surefire-reports/test
    - store_artifacts:
        path: target/surefire-reports/Suite
workflows:
  version: 2
  workflow:
    jobs:
    - build
      
