version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    working_directory: ~/hello-world
    steps:
    - checkout
    - restore_cache:
        key: hello-world-{{ checksum "pom.xml" }}
    - run: mvn dependency:go-offline
    - save_cache:
        paths:
        - ~/.m2
        key: hello-world-{{ checksum "pom.xml" }}
    - run: mvn package
     steps:
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit     
    
   
